name: Pipeline Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonagem do Projeto
        uses: actions/checkout@v3

      - name: Configuração do Pyton
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
    
      - name: Instalar Depencia do Projeto
        run: |
          pyton -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt

      - name: Executar testes do Robot Framework
        run: |
          robot -d results tests/

