name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Baixar e configurar WebDriver (Chrome e ChromeDriver)
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=$(which chromedriver)" >> $GITHUB_ENV

      - name: Executar testes do Robot Framework
        run: |
          robot -d results tests/

      - name: Upload de relatórios
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Relatórios Robot Framework
          path: results/
